package LeetCode.BinarySearch.P528RandomPickWithWeight;

import java.util.Random;

/*
 * P528. Random Pick with Weight - Medium
 * 
 * You are given a 0-indexed array of positive integers w where w[i] describes the weight of the ith index.
 * 
 * You need to implement the function pickIndex(), which randomly picks an index in the range 
 * [0, w.length - 1] (inclusive) and returns it. The probability of picking an index i is w[i] / sum(w).
 * 
 * For example, if w = [1, 3], the probability of picking index 0 is 1 / (1 + 3) = 0.25 
 * (i.e., 25%), and the probability of picking index 1 is 3 / (1 + 3) = 0.75 (i.e., 75%).
 * 
 * Approach - Linear seach, Prefix Sum
 */
public class P528RandomPickWithWeightLinearSearch {

	int[] prefix;
	Random random;

	// Linear Search
	// Here we randomly pick up a value based on the weight of each value.
	// The task is to do sampling with weight. For an input [1,9], when we pick a
	// number, the chance that 9 times out of 10, we should pick 9 as answer.
	// Probability of picking a number is picked is proportional to value of number.
	// with regards to total sum of numbers. We simulate it in our algorithm.
	// The number line is constructed by chaining up all values together. We denote
	// the list of numbers is denoted as [w1,w2,.wn]. Starting from beginning of
	// line, we then represent offsets for each range K as (∑(1->k)wi, ∑(1->k+1)wi)
	// The offsets of the ranges are the prefix sums from the number sequence.
	// For each numbers in sequence, the prefix/cumulative sum = sum of all previous
	// numbers + number itself. The prefix sums would be strictly monotonically
	// increasing, if all numbers are positive. To find a number in line is to find
	// an offset to place the number, this is called offset target. Once we randomly
	// generate the target offset, we find the range for this target. The problem is
	// rephrased: Given offset list(prefix sum) and target offset, our task is to
	// fit the target offset into the list so that ascending order is maintained.
	// We need to randomly generate a target offset for the ball/number which should
	// ensure that each point on the line has an equal opportunity to be the target
	// offset for the ball/number. For this Random() function is used to generate a
	// random value between 0 and 1. This value is scaled to the entire range of
	// line, by multiplying it with the size of the range(prefix[n-1]). This scaled
	// random value is the target offset. Random.nextInt(range), can also generate a
	// random integer from a given range [0, lastVal). Random function can also work
	// for the case where the weights are float values.
	// Algo: We create a list of prefix sums from a given list of numbers in
	// Constructor so that we don't have to generate it again and again when we
	// invoke pickIndex(). We get total sum of input numbers = prefix[n - 1] used to
	// scale up the random number.
	// For pickIndex(), we scale up the random number(nextFloat)[0,1) which is the
	// target offset. We then scan the prefix sums by linear search and find the 1st
	// prefix sum > target. If random number is generated by nextInt(total sum) + 1,
	// then we find 1st prefix sum >= target. The index of this prefix sum is where
	// target will come and is returned.
	// Time complexity - O(n), for constructor and pickIndex() it takes O(n) time
	// for prefix array.
	// Space Complexity - O(n), for prefix sums.
	public P528RandomPickWithWeightLinearSearch(int[] w) {
		random = new Random();
		int n = w.length;
		prefix = new int[n];
		prefix[0] = w[0];
		for (int i = 1; i < n; i++) {
			prefix[i] = prefix[i - 1] + w[i];
		}
	}

	public int pickIndex() {
		int n = prefix.length;
		// [0.0f, 1.0f)
//		float randomNum = random.nextFloat();
		// [0, 4.0f) <
//		float target = randomNum * prefix[n - 1];
//		for (int i = 0; i < n; i++) {
//			if (target < prefix[i]) {
//				return i;
//			}
//		}
		// [1, 4] | 1 2 3 4 <=
		int target = random.nextInt(prefix[n - 1]) + 1;
		for (int i = 0; i < n; i++) {
			if (target <= prefix[i]) {
				return i;
			}
		}
		return n - 1;
	}

	public static void main(String[] args) {
		int[] w = { 1, 3 };
		P528RandomPickWithWeightLinearSearch solution = new P528RandomPickWithWeightLinearSearch(w);

		int weightIndex = solution.pickIndex();
		System.out.println("The weight picked randomly is: " + weightIndex);
	}

}
